### ISSUE TITLE
--dump in help, not --digest

### ISSUE THREAD

**Issue by ralphyz** [spencerdodd/kernelpop#23]
The help (./kernelpop.py --help) says to use --dump for json...it is actually --digest

**Comment by spencerdodd** [comment]
Thanks! Fixed as of https://github.com/spencerdodd/kernelpop/commit/95eef9fbb52be752b8f641d79b069e219dcd377c

**Comment by ralphyz** [comment]
Awesome! Thanks for the quick fix!
